name: Fetch Specific Rules Daily

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-and-integrate-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 确保有写入权限
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Create Rule directory
        run: mkdir -p Rule

      - name: Fetch and Integrate AI Rules
        run: |
          echo "# AI Rules - Fetched on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > Rule/Ai.list
          echo "" >> Rule/Ai.list

          # OpenAI.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/OpenAI/OpenAI.list" >> Rule/Ai.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list | grep -v '^#' >> Rule/Ai.list
          echo "" >> Rule/Ai.list

          # Gemini.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Gemini/Gemini.list" >> Rule/Ai.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Gemini/Gemini.list | grep -v '^#' >> Rule/Ai.list
          echo "" >> Rule/Ai.list

          # Claude.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Claude/Claude.list" >> Rule/Ai.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Claude/Claude.list | grep -v '^#' >> Rule/Ai.list
          echo "" >> Rule/Ai.list

          # 新增：添加自定义规则到 Ai.list 的末尾
          echo "# Custom rule added by workflow" >> Rule/Ai.list
          echo "DOMAIN-KEYWORD,apple-relay" >> Rule/Ai.list
          echo "" >> Rule/Ai.list # 确保文件末尾有一个空行

          echo "Ai.list generated successfully in Rule/ with comments removed and custom rule added."

      - name: Fetch and Integrate Global Rules
        run: |
          echo "# Global Rules - Fetched on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > Rule/global.list
          echo "" >> Rule/global.list

          # Google.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Google/Google.list" >> Rule/global.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list | grep -v '^#' >> Rule/global.list
          echo "" >> Rule/global.list

          # GitHub.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/GitHub/GitHub.list" >> Rule/global.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GitHub/GitHub.list | grep -v '^#' >> Rule/global.list
          echo "" >> Rule/global.list

          # Twitter.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Twitter/Twitter.list" >> Rule/global.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitter/Twitter.list | grep -v '^#' >> Rule/global.list
          echo "" >> Rule/global.list

          # TikTok.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/TikTok/TikTok.list" >> Rule/global.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/TikTok/TikTok.list | grep -v '^#' >> Rule/global.list
          echo "" >> Rule/global.list

          # 新增：添加自定义规则到 global.list 的末尾
          echo "# Custom rule added by workflow" >> Rule/global.list
          echo "DOMAIN-KEYWORD,diabrowser" >> Rule/global.list
          echo "" >> Rule/global.list # 确保文件末尾有一个空行

          echo "global.list generated successfully in Rule/ with comments removed and custom rule added."

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Rule/Ai.list Rule/global.list
          if git diff --staged --quiet; then
            echo "No changes to commit for Ai.list or global.list in Rule/."
          else
            git commit -m "Update Ai.list and global.list in Rule/ folder - $(date -u +'%Y-%m-%d')"
            git push
          fi
