name: Fetch Specific Rules Daily

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-and-integrate-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 确保有写入权限
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Create Rule directory
        run: mkdir -p Rule

      - name: Fetch and Integrate AI Rules
        run: |
          echo "# AI Rules - Fetched on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > Rule/Ai.list
          echo "" >> Rule/Ai.list

          # OpenAI.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/OpenAI/OpenAI.list" >> Rule/Ai.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list | grep -v '^#' >> Rule/Ai.list
          echo "" >> Rule/Ai.list

          # Gemini.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Gemini/Gemini.list" >> Rule/Ai.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Gemini/Gemini.list | grep -v '^#' >> Rule/Ai.list
          echo "" >> Rule/Ai.list

          # Claude.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Claude/Claude.list" >> Rule/Ai.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Claude/Claude.list | grep -v '^#' >> Rule/Ai.list
          echo "" >> Rule/Ai.list

          # Custom rule for Ai.list
          echo "# Custom rule added by workflow" >> Rule/Ai.list
          echo "DOMAIN-KEYWORD,apple-relay" >> Rule/Ai.list
          echo "" >> Rule/Ai.list

          echo "Ai.list generated successfully in Rule/ with comments removed and custom rule added."

      - name: Fetch and Integrate Global Rules
        run: |
          echo "# Global Rules - Fetched on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > Rule/global.list
          echo "" >> Rule/global.list

          # Google.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Google/Google.list" >> Rule/global.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list | grep -v '^#' >> Rule/global.list
          echo "" >> Rule/global.list

          # GitHub.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/GitHub/GitHub.list" >> Rule/global.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GitHub/GitHub.list | grep -v '^#' >> Rule/global.list
          echo "" >> Rule/global.list

          # Twitter.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Twitter/Twitter.list" >> Rule/global.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitter/Twitter.list | grep -v '^#' >> Rule/global.list
          echo "" >> Rule/global.list

          # TikTok.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/TikTok/TikTok.list" >> Rule/global.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/TikTok/TikTok.list | grep -v '^#' >> Rule/global.list
          echo "" >> Rule/global.list

          # Custom rule for global.list
          echo "# Custom rule added by workflow" >> Rule/global.list
          echo "DOMAIN-KEYWORD,diabrowser" >> Rule/global.list
          echo "" >> Rule/global.list

          echo "global.list generated successfully in Rule/ with comments removed and custom rule added."

      - name: Fetch and Integrate SpoPaVo Rules # <-- 新增步骤
        run: |
          echo "# Spotify, PayPal, GoogleVoice Rules - Fetched on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > Rule/SpoPaVo.list
          echo "" >> Rule/SpoPaVo.list

          # Spotify.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/Spotify/Spotify.list" >> Rule/SpoPaVo.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Spotify/Spotify.list | grep -v '^#' >> Rule/SpoPaVo.list
          echo "" >> Rule/SpoPaVo.list

          # PayPal.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/PayPal/PayPal.list" >> Rule/SpoPaVo.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PayPal/PayPal.list | grep -v '^#' >> Rule/SpoPaVo.list
          echo "" >> Rule/SpoPaVo.list

          # GoogleVoice.list
          echo "# From: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Surge/GoogleVoice/GoogleVoice.list" >> Rule/SpoPaVo.list
          curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/GoogleVoice/GoogleVoice.list | grep -v '^#' >> Rule/SpoPaVo.list
          echo "" >> Rule/SpoPaVo.list

          echo "SpoPaVo.list generated successfully in Rule/ with comments removed."

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # 添加所有规则文件到 git
          git add Rule/Ai.list Rule/global.list Rule/SpoPaVo.list # <-- 修改：添加了 SpoPaVo.list
          if git diff --staged --quiet; then
            echo "No changes to commit for rule lists in Rule/."
          else
            # 更新 commit 信息
            git commit -m "Update Ai.list, global.list, and SpoPaVo.list in Rule/ folder - $(date -u +'%Y-%m-%d')" # <-- 修改 commit 信息
            git push
          fi
