name: Fetch Specific Rules Daily

on:
  schedule:
    - cron: '0 19 * * *'  # UTC+8 (北京时间凌晨3点)
  workflow_dispatch:

jobs:
  fetch-and-integrate-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Create Rule directory
        run: mkdir -p Rule

      - name: Fetch and Integrate Intelligence Rules
        run: |
          echo "# Intelligence Rules - Fetched on $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S GMT+8')" > Rule/Intelligence.list
          echo "" >> Rule/Intelligence.list

          {
            curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list
            curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Gemini/Gemini.list
            curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Claude/Claude.list
            curl -sL https://raw.githubusercontent.com/EAlyce/conf/refs/heads/main/Rule/OpenAI.list
            echo "DOMAIN-KEYWORD,apple-relay"
          } | grep -v '^#' | sort | uniq >> Rule/Intelligence.list

      - name: Fetch and Integrate CN Rules
        run: |
          echo "# CN Rules - Fetched on $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S GMT+8')" > Rule/CN.list
          echo "" >> Rule/CN.list

          {
            curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaMax/ChinaMax_All.list
            curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/MeiTuan/MeiTuan.list
            curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/WeChat/WeChat.list
            echo "DOMAIN-SUFFIX,example.cn"
          } | grep -v '^#' | sort | uniq >> Rule/CN.list

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add Rule/Intelligence.list Rule/CN.list
          if git diff --staged --quiet; then
            echo "No changes to commit for rule lists in Rule/."
          else
            COMMIT_TIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S GMT+8')
            git commit -m "Update rule lists - $COMMIT_TIME"
            git push
          fi
